/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateTerminalArgs } from "./CreateTerminalArgs";
import { UpdateTerminalArgs } from "./UpdateTerminalArgs";
import { DeleteTerminalArgs } from "./DeleteTerminalArgs";
import { TerminalCountArgs } from "./TerminalCountArgs";
import { TerminalFindManyArgs } from "./TerminalFindManyArgs";
import { TerminalFindUniqueArgs } from "./TerminalFindUniqueArgs";
import { Terminal } from "./Terminal";
import { TerminalService } from "../terminal.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Terminal)
export class TerminalResolverBase {
  constructor(
    protected readonly service: TerminalService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Terminal",
    action: "read",
    possession: "any",
  })
  async _terminalsMeta(
    @graphql.Args() args: TerminalCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Terminal])
  @nestAccessControl.UseRoles({
    resource: "Terminal",
    action: "read",
    possession: "any",
  })
  async terminals(
    @graphql.Args() args: TerminalFindManyArgs
  ): Promise<Terminal[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Terminal, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Terminal",
    action: "read",
    possession: "own",
  })
  async terminal(
    @graphql.Args() args: TerminalFindUniqueArgs
  ): Promise<Terminal | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Terminal)
  @nestAccessControl.UseRoles({
    resource: "Terminal",
    action: "create",
    possession: "any",
  })
  async createTerminal(
    @graphql.Args() args: CreateTerminalArgs
  ): Promise<Terminal> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Terminal)
  @nestAccessControl.UseRoles({
    resource: "Terminal",
    action: "update",
    possession: "any",
  })
  async updateTerminal(
    @graphql.Args() args: UpdateTerminalArgs
  ): Promise<Terminal | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Terminal)
  @nestAccessControl.UseRoles({
    resource: "Terminal",
    action: "delete",
    possession: "any",
  })
  async deleteTerminal(
    @graphql.Args() args: DeleteTerminalArgs
  ): Promise<Terminal | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
